### ISSUE TITLE
What is the license of this software?

### ISSUE THREAD

**Issue by EchedeyLR** [wlonk/wheretofind.me#176]
I don't see such license file.

**Comment by ojacobson** [comment]
This software is copyright 2019 and onwards by its authors. There is no license file because it is not offered under a standing license.

Informally, interested individuals are free to download and inspect the source at their pleasure. We can't really stop you from doing that, and we wouldn't even if we could: showing the world how the service works is an important tool for accountability and transparency. However, we ask that any organization or group wishing to make use of this code, other than via the wheretofind.me service, to please reach out to ask permission first.
