### ISSUE TITLE
Add user avatars

### ISSUE THREAD

**Issue by AlanDeSmet** [wlonk/wheretofind.me#92]
User avatars can be useful for helping to identify people. It would be nice to see a larger avatar when looking at someone's page, and smaller avatars on the Follows, Followers and search results pages.

**Self Hosting**

Self hosting is awesome as it maximizes option. However given the bandwidth, storage, policing for DMCA complaints and outright inappropriate stuff, perhaps something for later.

**Gravatar**

An easier option is Gravatar. They allow filtering by "rating", support a variety of sizes, and you can provide your own default (perhaps just the WTFM logo?). On the down side, it means anyone wanting an avatar who isn't already using Gravatar needs to set up an account there.

You will need the user's email address to find their Gravatar address, and it's possible that they address they signed up with isn't the one they have a Gravatar registered with. Also, not everyone may want to opt in. So I'd add a new setting "Email address to use for Gravatar", perhaps on https://wheretofind.me/aliases/ , which with the addition of "Include me in search results" is starting to look like a Settings page.

I suspect this is a `good first issue`.  I'd be happy to take a run at it, but I don't know when I'll have the time.

**Comment by wlonk** [comment]
We have a notion to do this under #31, but I like this as a more-detailed plan regarding letting users opt-in. I decided a bit ago that I don't want to handle user uploads, and would rather use Gravatar.

I agree that once there are two user settings, we start to push towards a settings page. One thing I like about our current architecture is that it makes it easy to include settings _in the context where they're applicable_ and then also on a unified settings page, so that might be a thing to consider, down the road. For now, both are relevant at the Aliases page, so we can leave it there.

I'm happy to help you get a dev setup going if you wanna try to get a PR in on this, but of course, no pressure. Any contribution is welcome but not expected!
